"""Variable definitions for cfdb."""

from cfdb_vars.coord_vars import coord_var_defs
from cfdb_vars.data_vars import data_var_defs
from cfdb_vars.time_dtype_params import time_dtype_params as time_dtype_params

__version__ = '0.2.2'

var_defs = {**coord_var_defs, **data_var_defs}

short_name_map = {
    'lon': 'longitude',
    'lat': 'latitude',
    'height': 'height',
    'altitude': 'altitude',
    'time': 'time',
    'x': 'x',
    'y': 'y',
    'point': 'point',
    'line': 'line',
    'polygon': 'polygon',
    'modified_date': 'modified_date',
    'band': 'band',
    'censor_code': 'censor_code',
    'precip': 'precipitation',
    'air_temp': 'air_temperature',
    'wind_speed': 'wind_speed',
    'wind_direction': 'wind_direction',
    'u_wind': 'u_wind',
    'v_wind': 'v_wind',
    'relative_humidity': 'relative_humidity',
    'dew_temp': 'dew_point_temperature',
    'soil_temp': 'soil_temperature',
    'lwe_soil_moisture': 'lwe_soil_moisture',
    'surface_pressure': 'surface_pressure',
    'specific_humidity': 'specific_humidity',
    'mixing_ratio': 'mixing_ratio',
    'shortwave_radiation': 'shortwave_radiation',
    'longwave_radiation': 'longwave_radiation',
    'snow_depth': 'snow_depth',
    'mslp': 'mslp',
    'vorticity': 'vorticity',
    'vertical_velocity': 'vertical_velocity',
    'sensible_heat_flux': 'sensible_heat_flux',
    'moisture_flux': 'moisture_flux',
    'albedo': 'albedo',
    'emissivity': 'emissivity',
    'terrain_height': 'terrain_height',
    'potential_temperature': 'potential_temperature',
    'equivalent_potential_temperature': 'equivalent_potential_temperature',
    'land_use_modis': 'land_use_modis',
    'geopotential_height': 'geopotential_height',
    'land_sea_mask': 'land_sea_mask',
    'sea_ice': 'sea_ice',
    'sea_surface_temp': 'sea_surface_temp',
    'snow_water_equiv': 'snow_water_equiv',
    'soil_moisture': 'soil_moisture',
    'soil_layer_temp': 'soil_layer_temp',
    'depth': 'depth',
    'pressure': 'pressure',
    'pwat': 'pwat',
    'vimf_u': 'vimf_u',
    'vimf_v': 'vimf_v',
    'skin_temp': 'skin_temperature',
    'snow_layer_temp': 'snow_layer_temperature',
    'ice_surface_temp': 'ice_surface_temperature',
    'cape': 'cape',
    'snow_density': 'snow_density',
    'snow_albedo': 'snow_albedo',
    'skin_reservoir_content': 'skin_reservoir_content',
    'surface_roughness': 'surface_roughness',
    'surface_roughness_heat': 'surface_roughness_heat',
    'charnock': 'charnock',
    'total_cloud_cover': 'total_cloud_cover',
    'low_cloud_cover': 'low_cloud_cover',
    'medium_cloud_cover': 'medium_cloud_cover',
    'high_cloud_cover': 'high_cloud_cover',
    'cloud_cover': 'cloud_cover',
    'total_column_water': 'total_column_water',
    'total_column_liquid_water': 'total_column_liquid_water',
    'total_column_ice_water': 'total_column_ice_water',
    'total_column_rain_water': 'total_column_rain_water',
    'total_column_snow_water': 'total_column_snow_water',
    'total_column_ozone': 'total_column_ozone',
    'divergence': 'divergence',
    'potential_vorticity': 'potential_vorticity',
    'ozone_mixing_ratio': 'ozone_mixing_ratio',
    'cloud_liquid_water_content': 'cloud_liquid_water_content',
    'cloud_ice_water_content': 'cloud_ice_water_content',
    'rain_water_content': 'rain_water_content',
    'snow_water_content': 'snow_water_content',
    'boundary_layer_height': 'boundary_layer_height',
    'surface_stress_east': 'surface_stress_east',
    'surface_stress_north': 'surface_stress_north',
    'uv_albedo_direct': 'uv_albedo_direct',
    'uv_albedo_diffuse': 'uv_albedo_diffuse',
    'nir_albedo_direct': 'nir_albedo_direct',
    'nir_albedo_diffuse': 'nir_albedo_diffuse',
    'leaf_area_index_low': 'leaf_area_index_low',
    'leaf_area_index_high': 'leaf_area_index_high',
    'low_vegetation_cover': 'low_vegetation_cover',
    'high_vegetation_cover': 'high_vegetation_cover',
    'low_vegetation_type': 'low_vegetation_type',
    'high_vegetation_type': 'high_vegetation_type',
    'lake_cover': 'lake_cover',
    'lake_depth': 'lake_depth',
    'lake_bottom_temp': 'lake_bottom_temperature',
    'lake_total_layer_temp': 'lake_total_layer_temperature',
    'lake_shape_factor': 'lake_shape_factor',
    'lake_ice_temp': 'lake_ice_temperature',
    'lake_ice_depth': 'lake_ice_depth',
    'soil_type': 'soil_type',
    'std_dev_orography': 'std_dev_orography',
    'std_dev_filtered_orography': 'std_dev_filtered_orography',
    'orography_anisotropy': 'orography_anisotropy',
    'orography_angle': 'orography_angle',
    'orography_slope': 'orography_slope',
}
